#!/usr/bin/env ruby

require 'highline/import'
require 'github/markdown'

def print_challenge_description challenge
  File.open("./challenges/#{challenge}/ChallengeDescription", "rb").read
end

def challenge_menu
  challenge_list = Dir.entries('./challenges').select {|entry| File.directory? File.join('./challenges',entry) and !(entry =='.' || entry == '..') }
  choose do |menu|
      menu.prompt = "What challenge would you like to work on?  "

      for challenge in challenge_list
        challenge_name = challenge.slice(challenge.index("-")+1..-1)
        menu.choice(challenge_name) { say(print_challenge_description challenge) }
      end
    end
end

challenge_menu
