#!/usr/bin/env ruby

require 'highline/import'
require 'github/markdown'

challenge_list = Dir.entries('./challenges').select {|entry| File.directory? File.join('./challenges',entry) and !(entry =='.' || entry == '..') }

choose do |menu|
    menu.prompt = "What challenge would you like to work on?  "

    for challenge in challenge_list
      challenge_name = challenge.slice(challenge.index("-")+1..-1)
      menu.choice(challenge_name) { say(File.open("./challenges/#{challenge}/ChallengeDescription", "rb").read) }
    end
  end